name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Instalar dependencias
      run: sudo apt update && sudo apt install -y g++ make

    - name: Compilar y probar
      run: |
        wget https://github.com/catchorg/Catch2/releases/download/v3.5.3/catch_amalgamated.hpp
        mkdir build
        g++ -std=c++17 test/test_solution.cpp -o build/tests
        ./build/tests
